### ISSUE TITLE
Impossible to remove xfconf property without setting Playbook value

### ISSUE THREAD

**Issue by danie1k** [ansible-collections/community.general#1329]
##### SUMMARY
Intuitively, the `value` should not be needed for property removal (`state: absent`), but unfortunately it is required due to bug in the following line:

https://github.com/ansible-collections/community.general/blob/d95910963b87e9efba2aed1b527a2f8e4d6ee7ae/plugins/modules/system/xfconf.py#L289

If `value` is not given in playbook, the value of `xfconf.value` is None, but in Python:
```python
>>> set(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not iterable
```

Related issue: #1328

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
plugins/modules/system/xfconf.py

##### ANSIBLE VERSION
*Not relevant.*

##### CONFIGURATION
*Not relevant.*

##### OS / ENVIRONMENT
*Not relevant.*

##### STEPS TO REPRODUCE
In my case it was
```yaml
- community.general.xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-4
    state: absent
```

But it should not matter what you want to remove.

##### EXPECTED RESULTS
- Less broad try...except block
- Working `state: absent` without need to set `value`.
- More readable IF statement code

#### ACTUAL RESULTS
```
fatal: [x.x.x.x]: FAILED! => {"changed": false, "msg": "Failed with exception: 'NoneType' object is not iterable"}
```

**Comment by danie1k** [comment]
Minimal version that works is:
```python
- community.general.xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-4
    state: absent
    value: ""
    value_type: string
```

**Comment by russoz** [comment]
Thanks for that one too, I also believe it will be fixed by #1322 , as `value` is not required for the `absent` state.

**Comment by russoz** [comment]
@danie1k community.general 1.3.0 that's been just released contains the fix.

resolved_by_pr #1322

**Comment by russoz** [comment]
@danie1k can you please confirm this is no longer a problem?

**Comment by russoz** [comment]
close_me I will assume this is OK per the code, but in case it still fails, please just reopen the issue. Thx

**Comment by danie1k** [comment]
@russoz, sorry for lack of feedback. I was very busy lately. I'll check the latest version and let you know in a few days.

**Comment by russoz** [comment]
@danie1k  No worries mate, whenever you have the time. It seemed to be ok, but it's always nice to double check.

**Comment by danie1k** [comment]
For the record - I confirm that in version 1.3.0 xfconf module works smoothly :slightly_smiling_face:
