### ISSUE TITLE
Unable to use Proxmox Inventory Plugin with AWX

### ISSUE THREAD

**Issue by JohnCardenas** [ansible-collections/community.general#1644]
##### SUMMARY
The `community.general.proxmox` inventory plugin does not correctly respect fallback environment variables. It should be possible to define `PROXMOX_HOST`, `PROXMOX_USER`, and `PROXMOX_PASSWORD` to provide credentials without storing them in source control.

Because of this behavior, it is impossible to use with AWX without putting credentials into source control and exposing them.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.general.proxmox

##### ANSIBLE VERSION
```
ansible 2.9.15
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```
N/A
```

##### OS / ENVIRONMENT
AWX 16.0.0 running in official Docker images on Ubuntu 20.04 LTS.

##### STEPS TO REPRODUCE
1. Configure a Credential Type in AWX with the following injectors:
```yaml
env:
  PROXMOX_HOST: '{{ PROXMOX_HOST }}'
  PROXMOX_USER: '{{ PROXMOX_USER }}'
  PROXMOX_PASSWORD: '{{ PROXMOX_PASSWORD }}'
```
2. Create a Project with a `proxmox.yml` file containing the following:
```yaml
plugin: community.general.proxmox
```

3. Configure a Credential based on the custom Credential Type, attach it to an Inventory Source from project. Start the inventory sync.

##### EXPECTED RESULTS
Inventory loads successfully into Ansible AWX.

##### ACTUAL RESULTS
Inventory fails to load due to settings being marked as required.

```
ansible-inventory 2.9.15
  config file = /tmp/awx_29_pt5il9gf/project/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
Using /tmp/awx_29_pt5il9gf/project/ansible.cfg as config file
setting up inventory plugins
Skipping due to inventory source not ending in "proxmox.yaml" nor "proxmox.yml"
ansible_collections.community.general.plugins.inventory.proxmox declined parsing /tmp/awx_29_pt5il9gf/project/collections/requirements.yml as it did not pass its verify_file() method
[WARNING]: Unable to parse
/tmp/awx_29_pt5il9gf/project/collections/requirements.yml as an inventory
source
[WARNING]: Unable to parse /tmp/awx_29_pt5il9gf/project/collections as an
inventory source
setting up inventory plugins
[WARNING]:  * Failed to parse /tmp/awx_29_pt5il9gf/project/proxmox.yml with
ansible_collections.community.general.plugins.inventory.proxmox plugin: No
setting was provided for required configuration plugin_type: inventory plugin:
ansible_collections.community.general.plugins.inventory.proxmox setting:
password
  File "/usr/lib/python3.6/site-packages/ansible/inventory/manager.py", line 280, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/tmp/awx_29_pt5il9gf/requirements_collections/ansible_collections/community/general/plugins/inventory/proxmox.py", line 340, in parse
    self._read_config_data(path)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/inventory/__init__.py", line 229, in _read_config_data
    self.set_options(direct=config)
  File "/usr/lib/python3.6/site-packages/ansible/plugins/__init__.py", line 75, in set_options
    self._options = C.config.get_plugin_options(get_plugin_class(self), self._load_name, keys=task_keys, variables=var_options, direct=direct)
  File "/usr/lib/python3.6/site-packages/ansible/config/manager.py", line 349, in get_plugin_options
    options[option] = self.get_config_value(option, plugin_type=plugin_type, plugin_name=name, keys=keys, variables=variables, direct=direct)
  File "/usr/lib/python3.6/site-packages/ansible/config/manager.py", line 418, in get_config_value
    keys=keys, variables=variables, direct=direct)
  File "/usr/lib/python3.6/site-packages/ansible/config/manager.py", line 506, in get_config_value_and_origin
    to_native(_get_entry(plugin_type, plugin_name, config)))
[WARNING]: Unable to parse /tmp/awx_29_pt5il9gf/project/proxmox.yml as an
inventory source
[WARNING]: Unable to parse /tmp/awx_29_pt5il9gf/project as an inventory source
ERROR! No inventory was parsed, please check your configuration and options.
```

**Comment by felixfontein** [comment]
I cannot find any reference in the source of the plugin that `PROXMOX_*` environment variables are supported. Are you sure this is a bug report, and not a feature request?

**Comment by JohnCardenas** [comment]
Hi @felixfontein ,

If I am not mistaken (and I am very likely to be, as I'm new to Ansible inventory plugins and not at all a Python developer), the code at https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/proxmox.py#L38 seems to indicate the `PROXMOX_*` environment variables are supported for fallback for the host, user, and password.

**Comment by felixfontein** [comment]
@JohnCardenas the module_utils is only used by some of the proxmox modules (not all of them though), but not by the inventory plugin.

**Comment by JohnCardenas** [comment]
@felixfontein - thanks for that. I've now seen how a couple other plugins do it, and I'll PR the env passthrough change. I'm going to go ahead and close this issue, since it is not a bug.

**Comment by felixfontein** [comment]
@JohnCardenas adding support for env variables for plugins is easier than for modules, so feel free to create a PR for that :)
