### ISSUE TITLE
Wrong module name referenced in example

### ISSUE THREAD

**Issue by marceloleitner** [ansible-collections/community.general#203]
https://github.com/ansible-collections/community.general/blob/2eee9f78a69f5dcb5798a904a7a565d1ddaf4f39/plugins/modules/net_tools/ip_netns.py#L49

It should be "ip_netns:" instead, and ditto for the other line as well.

**Comment by gundalow** [comment]
@marceloleitner Thanks for pointing this out.
Would you be interested in raising a PR (Pull Request) to update https://github.com/ansible-collections/community.general/blob/master/plugins/modules/net_tools/ip_netns.py

**Comment by Andersson007** [comment]
closed via https://github.com/ansible-collections/community.general/pull/207
