### ISSUE TITLE
Allow community.general.ldap_search to be used even in check mode

### ISSUE THREAD

**Issue by sabman3** [ansible-collections/community.general#3619]
### Summary

It looks like community.general.ldap_search does no return data if using check mode. You have to use "check_mode=no" to get data if testing. It's a search, so nothing should be changed anyways. So whether or not "--check" is used when calling the playbook the correct result should be returned. 

### Issue Type

Feature Idea

### Component Name

community.general.ldap_search

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by russoz** [comment]
@sabman3 this seems to be a very simple and straightforward change. If you would be willing to send a pull-request for that, we would be more than happy to assist you on that process.

**Comment by sabman3** [comment]
@russoz I'm working on it. This is my first time contributing to a public GitHub project. I think I got the procedure correct. Also want to verify my change work in both check mode and non-check mode so it's backwards compatible for those that did use check_mode no as a workaroung.

**Comment by russoz** [comment]
Will be checking soon
