### ISSUE TITLE
ansible fatal error when running on windows 7

### ISSUE THREAD

**Issue by hello-tty** [ansible-collections/community.general#6268]
### Summary

**I have 3 windows machines on which I do play-book (win 2016, win 10, win 7). On all machines, play-books work correctly for me except win 7. Actually, the error is:**

fatal: [
  WIN7.ANS.TEST
]: FAILED!=>{
  "ansible_facts": {
    
  },
  "changed": false,
  "failed_modules": {
    "setup": {
      "failed": true,
      "msg": "Unhandled exception while executing module: System.Threading.ThreadStartException: Thread failed to start. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Thread.StartInternal(IPrincipal principal, StackCrawlMark& stackMark)\r\n   at System.Threading.Thread.Start()\r\n   at System.Management.Automation.Runspaces.LocalPipeline.StartPipelineExecution()\r\n   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)\r\n   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)\r\n   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)\r\n   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)\r\n   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)\r\n   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)"
    }
  },
  "msg": "The following modules failed to execute: setup\n"
}

**Tell me what could be the problem?**

### Issue Type

Bug Report

### Component Name

pywinrm

### Ansible Version

ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tester/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Mar  8 2023, 18:40:28) [GCC 7.5.0]

### Community.general Version

usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: u'list' (choose from 'init', 'build', 'publish', 'install')

### Configuration

- hosts: windows
  tasks:

    - name: get license status
      win_shell: |
          $gg = Get-CimInstance SoftwareLicensingProduct -Filter "Name like 'Windows%'" |  where { $_.PartialProductKey }
            foreach ($i in $gg) {
            write-host $i.LicenseStatus
            }
      register: os_license_status

    - name: get list of software
      win_shell: |
          $software = get-wmiobject -class Win32_Product | select-object name,version
            foreach ($i in $software) {
            write-host "software_name: "$i.name ";" "software_version" $i.version
            }
      register: list_of_software
    - debug:
        var: list_of_software

    - set_fact:
        services: "ip: {{ ansible_ip_addresses[0] }}\nos_license: {{ os_license_status.stdout }}\ninstalled_software:\n{{list_of_software.stdout}}"
    - name: Print output to file
      ansible.builtin.copy:
        content: "{{services}}"
        dest: /home/tester/{{ansible_ip_addresses[0]}}
      delegate_to: localhost

- hosts: linux

  tasks:
    - name: test
      ansible.builtin.shell: |
        apt list --installed | grep office
      register: hello

    - set_fact:
        test_output: "{{hello.stdout}}"
    - name: Print output to file
      ansible.builtin.copy:
        content: "{{test_output}}"
        dest: /home/tester/linux
      delegate_to: localhost

### OS / Environment

Ubuntu 18.04.6 LTS

### Steps to Reproduce

ansible-playbook site.yml

### Expected Results

i expect the result i get from windows 10

PLAY [windows] *******************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [WIN10.ANS.TEST]

TASK [get license status] ********************************************************************************************************************************************************
changed: [WIN10.ANS.TEST]

TASK [get list of software] ******************************************************************************************************************************************************
changed: [WIN10.ANS.TEST]

TASK [debug] *********************************************************************************************************************************************************************
ok: [WIN10.ANS.TEST] => {
    "list_of_software": {
        "changed": true,
        "cmd": "$software = get-wmiobject -class Win32_Product | select-object name,version\n  foreach ($i in $software) {\n  write-host \"software_name: \"$i.name \";\" \"software_version\" $i.version\n  }",
        "delta": "0:00:01.921878",
        "end": "2023-03-31 02:44:35.244423",
        "failed": false,
        "rc": 0,
        "start": "2023-03-31 02:44:33.322544",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "software_name:  Microsoft Visual C++ 2019 X64 Additional Runtime - 14.24.28127 ; software_version 14.24.28127\nsoftware_name:  Microsoft Visual C++ 2019 X86 Additional Runtime - 14.24.28127 ; software_version 14.24.28127\nsoftware_name:  VMware Tools ; software_version 11.1.1.16303738\nsoftware_name:  Microsoft Visual C++ 2019 X64 Minimum Runtime - 14.24.28127 ; software_version 14.24.28127\nsoftware_name:  Microsoft Visual C++ 2019 X86 Minimum Runtime - 14.24.28127 ; software_version 14.24.28127\n",
        "stdout_lines": [
            "software_name:  Microsoft Visual C++ 2019 X64 Additional Runtime - 14.24.28127 ; software_version 14.24.28127",
            "software_name:  Microsoft Visual C++ 2019 X86 Additional Runtime - 14.24.28127 ; software_version 14.24.28127",
            "software_name:  VMware Tools ; software_version 11.1.1.16303738",
            "software_name:  Microsoft Visual C++ 2019 X64 Minimum Runtime - 14.24.28127 ; software_version 14.24.28127",
            "software_name:  Microsoft Visual C++ 2019 X86 Minimum Runtime - 14.24.28127 ; software_version 14.24.28127"
        ]
    }
}

TASK [set_fact] ******************************************************************************************************************************************************************
ok: [WIN10.ANS.TEST]

TASK [Print output to file] ******************************************************************************************************************************************************
ok: [WIN10.ANS.TEST -> localhost]

PLAY [linux] *********************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [linux_desktop]

TASK [test] **********************************************************************************************************************************************************************
changed: [linux_desktop]

TASK [set_fact] ******************************************************************************************************************************************************************
ok: [linux_desktop]

TASK [Print output to file] ******************************************************************************************************************************************************
ok: [linux_desktop -> localhost]

PLAY RECAP ***********************************************************************************************************************************************************************
WIN10.ANS.TEST             : ok=6    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
linux_desktop              : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

### Actual Results

```console (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by felixfontein** [comment]
1. This collection no longer supports Ansible 2.9 (which is in general End of Life).
2. None of the modules/actions mentioned in what you write are part of this collection.

You could ask on the user questions mailing list: https://groups.google.com/g/ansible-project/

But you are probably more successful if you first upgrade to a version of Ansible that's not End of Life.
