### ISSUE TITLE
Provide truly minimal stdout callback plugin

### ISSUE THREAD

**Issue by myllynen** [ansible-collections/community.general#6323]
### Summary

In very large environments with thousands of managed hosts (think of large data centers or edge) it can be very hard to interpret the results of a playbook run when even the play recap of the default stdout callback can be thousands of lines long.

Given that the environments Ansible is used to manage are only getting larger and larger it would be helpful to provide a truly minimal stdout callback plugin which would provide output only for hosts if something was changed, failed, or were unreachable. So nothing would be printed if a task or host was ok or skipped.

Optionally it would also be nice to minimize the diff output when using `ansible-playbook -D` and, if somehow possible and the user so requests, only display non-whitespace changes.

While the DIY plugin would allow doing something like what is described above partially it has a rather steep learning curve so that might not be a feasible option for everyone and I can't see a way to achieve this kind of "truly minimal" output with it.

Thanks.

### Issue Type

Feature Idea

### Component Name

callback

### Additional Information

Expected output could be something like this - of course other ideas and better suggestion would be warmly welcome:

```
$ ansible-playbook -i ./i test.yml
PLAY [Test play]
TASK [test.role : Gather needed facts]
TASK [test.role : Create file]
changed: [rhel-9-server.example.com]
TASK [test.role : Remove directory]
changed: [rhel-8-server.example.com]
TASK [test.role : Restart service]
changed: [rhel-9-server.example.com]
PLAY RECAP
<thousands of hosts listed>
PLAY SUMMARY
ok=9876 changed=2 unreachable=0 failed=0 skipped=123 rescued=0 ignored=321
```

So even if the inventory contained thousands of hosts the output is making it easy to see what tasks caused changes and where.

Perhaps a configuration option to print only tasks that had changes would also be worth considering as if the playbook is known then there's no value seeing each and every task being printed.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by flowerysong** [comment]
The default callback (and many callbacks derived from it, like `diy`) already allow you to disable display of `ok` and `skipped` tasks, and using a custom summary format without writing a separate callback is exactly the sort of thing that the `diy` callback is intended for.

Poking at it for a couple of minutes resulted in this:
```ini
[defaults]
stdout_callback = community.general.diy
display_skipped_hosts = false
display_ok_hosts = false

[callback_diy]
playbook_on_stats_msg = {% for i in [['ok'], ['changed'], ['dark', 'unreachable'], ['failures', 'failed'], ['skipped'], ['rescued'], ['ignored']] %}{{ i[1] | default(i[0]) }}={{ ansible_callback_diy.stats[i[0]].values() | sum }} {% endfor %}
```

Which when running a two-task play against 17 hosts produced this output:
```
PLAY [aws_ec2] *****************************************************************

TASK [Sometimes changed] *******************************************************
changed: [steady-deepone.jail.x.mail.umich.edu]
changed: [star-frances.builder.x.mail.umich.edu]
changed: [soigne-chthonian.syslog.x.mail.umich.edu]
changed: [strategic-shantak.dev.x.mail.umich.edu]
changed: [sure-hellhound.authn-relay.x.mail.umich.edu]
ok=34 changed=5 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0
```

(This could obviously be tweaked a bit, but since it's not actually something I need I just wanted to demonstrate the principle.)

**Comment by myllynen** [comment]
Thanks a lot, this indeed looks a pretty good start! The DIY examples I saw earlier were more confusing than helpful, this certainly makes it look like a feasible alternative. Inspired by your example I'll play around this in the coming days and if I was able to come up with anything useful I'll share the results here. Thanks.

**Comment by myllynen** [comment]
Sorry for the delay with this. I experimented a bit to create something that would match the initial idea but the result started to get overly long so perhaps it's better to keep things simple and at least initially I'll use the example you kindly shared. If I need something else I'll either try with diy again or just create a custom callback for local use.

Closing, thanks!
