### ISSUE TITLE
CHANGELOG entries regarding zabbix modules

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.general#751]
##### SUMMARY
There are entries related to zabbix modules present in the CHANGELOG.rst. These were carried over from ansible/ansible, but modules have been migrated to the community.zabbix.

Should I open PR for removing them from CHANGELOG.rst and changelogs/changelog.yaml? Will this work or does someone need to regenerate changelog via antsibull-changelog?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
CHANGELOG.rst

**Comment by felixfontein** [comment]
@D3DeFi I'm not sure why I added these fragments to this collection, either I got confused or there were wrong redirects around earlier. In any case, they definitely shouldn't be here. Can you create a PR to update changelogs/changelog.yaml and remove all fragments (and fragment filenames)? I'll update the PR with a antisbull-changelog run then, which updates the generated .rst file.

**Comment by D3DeFi** [comment]
I will tend to it :)

**Comment by D3DeFi** [comment]
explicitly mentioning #760 as you may be interested in merging it before 2.10 freeze
