### ISSUE TITLE
The gluster plugins have moved to their own collection

### ISSUE THREAD

**Issue by abadger** [ansible-collections/community.general#761]
##### SUMMARY
The RHHI team is maintaining the gluster plugins in their own collection:
* https://github.com/gluster/gluster-ansible-collection
* https://galaxy.ansible.com/gluster/gluster

We need to figure out how to migrate the content out of community.general and get the gluster.gluster collection into ansible.

It sounds like it might be too late to do this for 2.10 (The ansible-base-2.10 runtime.yml has already frozen for rc4.  Changing the locations in ansible-base-2.10 would probably be a backwards incompatible change.  community.general has released 1.0.0.  It should probably be considered a backwards incompatible change to move content out of community.general as it would add a new dependency to community.general on another collection.

We can probably do this for 2.11.0: although the exact requirements for new collections have not been nailed down, I think it's still fair to allow content which was in community.general and is being split into a different collection.

Are there ways we could get this into 2.10? Possibilities:
* community.general updates to 2.0.0 before ansible-2.10.0-beta1 with the content moved out.
* Perhaps we could allow the gluster collection in without the short names in 2.10?  It would be sort of like a tech-preview.... Want the old modules?  Use gluster_foo or the FQCN, community.general.gluster_foo.  Want the new modules? use the FQCN gluster.gluster.gluster_foo.  For community.general-2.0.0/ansible-2.11.0, we would then point all the modules at the gluster.gluster collection via community.general's runtime.yml file.
* The above idea but include it for 2.10.{1,2,3,etc} instead of 2.10.0.  We have said that we'd allow new features that are backwards compatible into ansible-2.10.x.  This might fall under that, although I hadn't planned on taking new collections inside of a release.  (Maybe it is okay because it's not a net-new collection?)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
* https://github.com/ansible-collections/community.general/tree/main/plugins/modules/storage/glusterfs
* https://github.com/gluster/gluster-ansible-collection

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by felixfontein** [comment]
See https://github.com/ansible/community/issues/539#issuecomment-673080605

**Comment by felixfontein** [comment]
PR to adjust ansible_builtin_redirect.yml is ansible/ansible#71240

**Comment by bmillemathias** [comment]
@abadger I think this issue can be closed
