### ISSUE TITLE
Clarify "Online" in online inventory plugin

### ISSUE THREAD

**Issue by jpmens** [ansible-collections/community.general#814]
##### SUMMARY

The documentation of the [online](https://github.com/ansible-collections/community.general/blob/main/plugins/inventory/online.py) inventory plugin states that its function is to `Get inventory hosts from Online`. I think it would be useful to clarify what "Online" (with a capital 'o') actually is. The word is rather generic...

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

online.py

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /Users/jpm/.ansible.cfg
  configured module search path = ['/etc/ansible/library', '/Users/jpm/Auto/projects/on-github/ansible/pdns_zone/library']
  ansible python module location = /usr/local/Cellar/ansible/2.9.10/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, Jul 12 2020, 17:59:33) [Clang 11.0.3 (clang-1103.0.32.62)]
```

**Comment by Akasurde** [comment]
resolved_by_pr https://github.com/ansible-collections/community.general/pull/1567
