### ISSUE TITLE
Edit on GitHub link broken on most (all?) pages

### ISSUE THREAD

**Issue by jpmens** [ansible-collections/community.general#815]
##### SUMMARY

At the top right of documentation pages, there is an "Edit on GitHub" link which is broken for (at least) a large number of pages. This hint is also contained in this documentation template:

```
HINT: Did you know the documentation has an "Edit on GitHub" link on every page ?
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

For example: [here](https://docs.ansible.com/ansible/latest/plugins/lookup/dig.html)

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = /Users/jpm/.ansible.cfg
  configured module search path = ['/etc/ansible/library', '/Users/jpm/Auto/projects/on-github/ansible/pdns_zone/library']
  ansible python module location = /usr/local/Cellar/ansible/2.9.10/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, Jul 12 2020, 17:59:33) [Clang 11.0.3 (clang-1103.0.32.62)]
```

**Comment by Akasurde** [comment]
This is a known issue and can be tracked using ansible/ansible#70267
