### ISSUE TITLE
redfish_command: Add OemParameters support in MultipartHTTPPushUpdate

### ISSUE THREAD

**Issue by cwhuang** [ansible-collections/community.general#8825]
### Summary

AMI BMC requires an additional OemParameters json when doing MultipartHTTPPushUpdate updates. It looks like #7331 but not exact the same. AMI BMC needs the OemParameters to be a separate json file instead of a key/value in UpdateParameters.
We suggest to add an option update_image_type to address it.

### Issue Type

Feature Idea

### Component Name

redfish_command

### Additional Information

```yaml (paste below)

Presumably it would be used like:
```
    - name: Multipart HTTP push with additional options
      community.general.redfish_command:
        category: Update
        command: MultipartHTTPPushUpdate
        baseuri: "{{ bmc_host }}"
        username: "{{ bmc_user }}"
        password: "{{ bmc_password }}"
        timeout: 600
        update_image_file:  bmc-image.ima
        update_image_type: BMC
        update_targets: /redfish/v1/UpdateService/FirmwareInventory/BMCImage1

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sseekamp** [comment]
@cwhuang are you sure that's the not the behavior that's present? My original PR referenced above was for an AMI BMC system as well.

https://github.com/ansible-collections/community.general/blob/e5ab4be82d880d9c4bc513835b7e204303846522/plugins/module_utils/redfish_utils.py#L1947-L1949
