### ISSUE TITLE
zypper_repository tests fail reliably

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.general#98]
##### SUMMARY
The zypper_repository tests currently fail reliably:

- https://app.shippable.com/github/ansible-collections/community.general/runs/359/23/tests https://app.shippable.com/github/ansible-collections/community.general/runs/359/24/tests
- https://app.shippable.com/github/ansible-collections/community.general/runs/358/23/tests https://app.shippable.com/github/ansible-collections/community.general/runs/358/24/tests
- https://app.shippable.com/github/ansible-collections/community.general/runs/357/23/tests https://app.shippable.com/github/ansible-collections/community.general/runs/357/24/tests
- https://app.shippable.com/github/ansible-collections/community.general/runs/356/31/tests https://app.shippable.com/github/ansible-collections/community.general/runs/356/32/tests
- https://app.shippable.com/github/ansible-collections/community.general/runs/354/31/tests https://app.shippable.com/github/ansible-collections/community.general/runs/354/32/tests
- https://app.shippable.com/github/ansible-collections/community.general/runs/353/31/tests https://app.shippable.com/github/ansible-collections/community.general/runs/353/32/tests
- https://app.shippable.com/github/ansible-collections/community.general/runs/352/31/tests https://app.shippable.com/github/ansible-collections/community.general/runs/352/32/tests
- https://app.shippable.com/github/ansible-collections/community.general/runs/351/31/tests https://app.shippable.com/github/ansible-collections/community.general/runs/351/32/tests

Because of that they were disabled in #96 

CC @matze as module author/maintainer.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zypper_repository

##### ANSIBLE VERSION
```paste below
devel
```

**Comment by mattclay** [comment]
This is most likely an issue with the test containers used by `ansible-test`. It will hopefully be resolved once https://github.com/ansible/ansible/issues/68783 is done.

**Comment by felixfontein** [comment]
Fixed by #139.
