### ISSUE TITLE
Slack Notification Channel Start WIth Update

### ISSUE THREAD

**Issue by jvanderaa** [ansible-collections/community.general#987]
##### SUMMARY
When attempting to post to a channel ID that starts with G or D the module fails unable to post.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.general.slack

##### ANSIBLE VERSION

```paste below
2.9.12
```

##### OS / ENVIRONMENT

Ansible on MacOS/Tower/Ubuntu

##### STEPS TO REPRODUCE

1. Created a PB that would post to slack
2. Attempted to use a private channel ID beginning with G, fails

```yaml

```

##### EXPECTED RESULTS

I would expect the message would post

##### ACTUAL RESULTS

```paste below

```

**Comment by jvanderaa** [comment]
Per https://api.slack.com/docs/conversations-api#working-with-shared-channels the shared channesl can start with C, G, or D. This should get updated on this: https://github.com/ansible-collections/community.general/blob/main/plugins/modules/notification/slack.py#L282

to support the additional starts with.

**Comment by jvanderaa** [comment]
Looks fixed in current main.

**Comment by felixfontein** [comment]
As you noticed it is fixed in `main`. The fix will be included in community.general 1.2.0, and thus in Ansible 2.10.1. AFAIK the fix has not been backported to ansible/ansible's stable-2.9 branch, so it won't show up in 2.9.x.

**Comment by jvanderaa** [comment]
I'm good with only using the collection version. I had an outdated version of it as I needed the work from the first week of September a touch earlier. Thank you!
